#pragma once

#include <cstddef>
#include <cstdint>

namespace printdeck::platform::audio_assets {

struct CompressedSample {
  const std::uint8_t* begin;
  const std::uint8_t* end;
  std::size_t decoded_size;
};

extern const std::uint8_t modern_startup_start[] asm("_binary_modern_startup_adpcm_gz_start");
extern const std::uint8_t modern_startup_end[] asm("_binary_modern_startup_adpcm_gz_end");
extern const std::uint8_t modern_navigation_start[] asm("_binary_modern_navigation_adpcm_gz_start");
extern const std::uint8_t modern_navigation_end[] asm("_binary_modern_navigation_adpcm_gz_end");
extern const std::uint8_t modern_orientation_start[] asm("_binary_modern_orientation_adpcm_gz_start");
extern const std::uint8_t modern_orientation_end[] asm("_binary_modern_orientation_adpcm_gz_end");
extern const std::uint8_t modern_print_started_start[] asm("_binary_modern_print_started_adpcm_gz_start");
extern const std::uint8_t modern_print_started_end[] asm("_binary_modern_print_started_adpcm_gz_end");
extern const std::uint8_t modern_print_paused_start[] asm("_binary_modern_print_paused_adpcm_gz_start");
extern const std::uint8_t modern_print_paused_end[] asm("_binary_modern_print_paused_adpcm_gz_end");
extern const std::uint8_t modern_print_finished_start[] asm("_binary_modern_print_finished_adpcm_gz_start");
extern const std::uint8_t modern_print_finished_end[] asm("_binary_modern_print_finished_adpcm_gz_end");
extern const std::uint8_t modern_print_error_start[] asm("_binary_modern_print_error_adpcm_gz_start");
extern const std::uint8_t modern_print_error_end[] asm("_binary_modern_print_error_adpcm_gz_end");
extern const std::uint8_t modern_hms_alert_start[] asm("_binary_modern_hms_alert_adpcm_gz_start");
extern const std::uint8_t modern_hms_alert_end[] asm("_binary_modern_hms_alert_adpcm_gz_end");
extern const std::uint8_t modern_filament_attention_start[] asm("_binary_modern_filament_attention_adpcm_gz_start");
extern const std::uint8_t modern_filament_attention_end[] asm("_binary_modern_filament_attention_adpcm_gz_end");
extern const std::uint8_t modern_shutdown_countdown_start[] asm("_binary_modern_shutdown_countdown_adpcm_gz_start");
extern const std::uint8_t modern_shutdown_countdown_end[] asm("_binary_modern_shutdown_countdown_adpcm_gz_end");
extern const std::uint8_t modern_shutdown_start[] asm("_binary_modern_shutdown_adpcm_gz_start");
extern const std::uint8_t modern_shutdown_end[] asm("_binary_modern_shutdown_adpcm_gz_end");
extern const std::uint8_t modern_test_start[] asm("_binary_modern_test_adpcm_gz_start");
extern const std::uint8_t modern_test_end[] asm("_binary_modern_test_adpcm_gz_end");
extern const std::uint8_t arcade_startup_start[] asm("_binary_arcade_startup_adpcm_gz_start");
extern const std::uint8_t arcade_startup_end[] asm("_binary_arcade_startup_adpcm_gz_end");
extern const std::uint8_t arcade_navigation_start[] asm("_binary_arcade_navigation_adpcm_gz_start");
extern const std::uint8_t arcade_navigation_end[] asm("_binary_arcade_navigation_adpcm_gz_end");
extern const std::uint8_t arcade_orientation_start[] asm("_binary_arcade_orientation_adpcm_gz_start");
extern const std::uint8_t arcade_orientation_end[] asm("_binary_arcade_orientation_adpcm_gz_end");
extern const std::uint8_t arcade_print_started_start[] asm("_binary_arcade_print_started_adpcm_gz_start");
extern const std::uint8_t arcade_print_started_end[] asm("_binary_arcade_print_started_adpcm_gz_end");
extern const std::uint8_t arcade_progress_25_start[] asm("_binary_arcade_progress_25_adpcm_gz_start");
extern const std::uint8_t arcade_progress_25_end[] asm("_binary_arcade_progress_25_adpcm_gz_end");
extern const std::uint8_t arcade_progress_50_start[] asm("_binary_arcade_progress_50_adpcm_gz_start");
extern const std::uint8_t arcade_progress_50_end[] asm("_binary_arcade_progress_50_adpcm_gz_end");
extern const std::uint8_t arcade_progress_75_start[] asm("_binary_arcade_progress_75_adpcm_gz_start");
extern const std::uint8_t arcade_progress_75_end[] asm("_binary_arcade_progress_75_adpcm_gz_end");
extern const std::uint8_t arcade_print_paused_start[] asm("_binary_arcade_print_paused_adpcm_gz_start");
extern const std::uint8_t arcade_print_paused_end[] asm("_binary_arcade_print_paused_adpcm_gz_end");
extern const std::uint8_t arcade_print_finished_start[] asm("_binary_arcade_print_finished_adpcm_gz_start");
extern const std::uint8_t arcade_print_finished_end[] asm("_binary_arcade_print_finished_adpcm_gz_end");
extern const std::uint8_t arcade_print_error_start[] asm("_binary_arcade_print_error_adpcm_gz_start");
extern const std::uint8_t arcade_print_error_end[] asm("_binary_arcade_print_error_adpcm_gz_end");
extern const std::uint8_t arcade_hms_alert_start[] asm("_binary_arcade_hms_alert_adpcm_gz_start");
extern const std::uint8_t arcade_hms_alert_end[] asm("_binary_arcade_hms_alert_adpcm_gz_end");
extern const std::uint8_t arcade_filament_attention_start[] asm("_binary_arcade_filament_attention_adpcm_gz_start");
extern const std::uint8_t arcade_filament_attention_end[] asm("_binary_arcade_filament_attention_adpcm_gz_end");
extern const std::uint8_t arcade_shutdown_countdown_start[] asm("_binary_arcade_shutdown_countdown_adpcm_gz_start");
extern const std::uint8_t arcade_shutdown_countdown_end[] asm("_binary_arcade_shutdown_countdown_adpcm_gz_end");
extern const std::uint8_t arcade_shutdown_start[] asm("_binary_arcade_shutdown_adpcm_gz_start");
extern const std::uint8_t arcade_shutdown_end[] asm("_binary_arcade_shutdown_adpcm_gz_end");
extern const std::uint8_t arcade_test_start[] asm("_binary_arcade_test_adpcm_gz_start");
extern const std::uint8_t arcade_test_end[] asm("_binary_arcade_test_adpcm_gz_end");
extern const std::uint8_t scifi_startup_start[] asm("_binary_scifi_startup_adpcm_gz_start");
extern const std::uint8_t scifi_startup_end[] asm("_binary_scifi_startup_adpcm_gz_end");
extern const std::uint8_t scifi_navigation_start[] asm("_binary_scifi_navigation_adpcm_gz_start");
extern const std::uint8_t scifi_navigation_end[] asm("_binary_scifi_navigation_adpcm_gz_end");
extern const std::uint8_t scifi_orientation_start[] asm("_binary_scifi_orientation_adpcm_gz_start");
extern const std::uint8_t scifi_orientation_end[] asm("_binary_scifi_orientation_adpcm_gz_end");
extern const std::uint8_t scifi_print_started_start[] asm("_binary_scifi_print_started_adpcm_gz_start");
extern const std::uint8_t scifi_print_started_end[] asm("_binary_scifi_print_started_adpcm_gz_end");
extern const std::uint8_t scifi_progress_25_start[] asm("_binary_scifi_progress_25_adpcm_gz_start");
extern const std::uint8_t scifi_progress_25_end[] asm("_binary_scifi_progress_25_adpcm_gz_end");
extern const std::uint8_t scifi_progress_50_start[] asm("_binary_scifi_progress_50_adpcm_gz_start");
extern const std::uint8_t scifi_progress_50_end[] asm("_binary_scifi_progress_50_adpcm_gz_end");
extern const std::uint8_t scifi_progress_75_start[] asm("_binary_scifi_progress_75_adpcm_gz_start");
extern const std::uint8_t scifi_progress_75_end[] asm("_binary_scifi_progress_75_adpcm_gz_end");
extern const std::uint8_t scifi_print_paused_start[] asm("_binary_scifi_print_paused_adpcm_gz_start");
extern const std::uint8_t scifi_print_paused_end[] asm("_binary_scifi_print_paused_adpcm_gz_end");
extern const std::uint8_t scifi_print_finished_start[] asm("_binary_scifi_print_finished_adpcm_gz_start");
extern const std::uint8_t scifi_print_finished_end[] asm("_binary_scifi_print_finished_adpcm_gz_end");
extern const std::uint8_t scifi_print_error_start[] asm("_binary_scifi_print_error_adpcm_gz_start");
extern const std::uint8_t scifi_print_error_end[] asm("_binary_scifi_print_error_adpcm_gz_end");
extern const std::uint8_t scifi_hms_alert_start[] asm("_binary_scifi_hms_alert_adpcm_gz_start");
extern const std::uint8_t scifi_hms_alert_end[] asm("_binary_scifi_hms_alert_adpcm_gz_end");
extern const std::uint8_t scifi_filament_attention_start[] asm("_binary_scifi_filament_attention_adpcm_gz_start");
extern const std::uint8_t scifi_filament_attention_end[] asm("_binary_scifi_filament_attention_adpcm_gz_end");
extern const std::uint8_t scifi_shutdown_countdown_start[] asm("_binary_scifi_shutdown_countdown_adpcm_gz_start");
extern const std::uint8_t scifi_shutdown_countdown_end[] asm("_binary_scifi_shutdown_countdown_adpcm_gz_end");
extern const std::uint8_t scifi_shutdown_start[] asm("_binary_scifi_shutdown_adpcm_gz_start");
extern const std::uint8_t scifi_shutdown_end[] asm("_binary_scifi_shutdown_adpcm_gz_end");
extern const std::uint8_t clean_navigation_start[] asm("_binary_clean_navigation_adpcm_gz_start");
extern const std::uint8_t clean_navigation_end[] asm("_binary_clean_navigation_adpcm_gz_end");
extern const std::uint8_t clean_orientation_start[] asm("_binary_clean_orientation_adpcm_gz_start");
extern const std::uint8_t clean_orientation_end[] asm("_binary_clean_orientation_adpcm_gz_end");
extern const std::uint8_t clean_shutdown_countdown_start[] asm("_binary_clean_shutdown_countdown_adpcm_gz_start");
extern const std::uint8_t clean_shutdown_countdown_end[] asm("_binary_clean_shutdown_countdown_adpcm_gz_end");
extern const std::uint8_t clean_test_start[] asm("_binary_clean_test_adpcm_gz_start");
extern const std::uint8_t clean_test_end[] asm("_binary_clean_test_adpcm_gz_end");
extern const std::uint8_t voice_en_startup_start[] asm("_binary_voice_en_startup_adpcm_gz_start");
extern const std::uint8_t voice_en_startup_end[] asm("_binary_voice_en_startup_adpcm_gz_end");
extern const std::uint8_t voice_en_print_started_start[] asm("_binary_voice_en_print_started_adpcm_gz_start");
extern const std::uint8_t voice_en_print_started_end[] asm("_binary_voice_en_print_started_adpcm_gz_end");
extern const std::uint8_t voice_en_progress_25_start[] asm("_binary_voice_en_progress_25_adpcm_gz_start");
extern const std::uint8_t voice_en_progress_25_end[] asm("_binary_voice_en_progress_25_adpcm_gz_end");
extern const std::uint8_t voice_en_progress_50_start[] asm("_binary_voice_en_progress_50_adpcm_gz_start");
extern const std::uint8_t voice_en_progress_50_end[] asm("_binary_voice_en_progress_50_adpcm_gz_end");
extern const std::uint8_t voice_en_progress_75_start[] asm("_binary_voice_en_progress_75_adpcm_gz_start");
extern const std::uint8_t voice_en_progress_75_end[] asm("_binary_voice_en_progress_75_adpcm_gz_end");
extern const std::uint8_t voice_en_print_paused_start[] asm("_binary_voice_en_print_paused_adpcm_gz_start");
extern const std::uint8_t voice_en_print_paused_end[] asm("_binary_voice_en_print_paused_adpcm_gz_end");
extern const std::uint8_t voice_en_print_finished_start[] asm("_binary_voice_en_print_finished_adpcm_gz_start");
extern const std::uint8_t voice_en_print_finished_end[] asm("_binary_voice_en_print_finished_adpcm_gz_end");
extern const std::uint8_t voice_en_print_error_start[] asm("_binary_voice_en_print_error_adpcm_gz_start");
extern const std::uint8_t voice_en_print_error_end[] asm("_binary_voice_en_print_error_adpcm_gz_end");
extern const std::uint8_t voice_en_hms_alert_start[] asm("_binary_voice_en_hms_alert_adpcm_gz_start");
extern const std::uint8_t voice_en_hms_alert_end[] asm("_binary_voice_en_hms_alert_adpcm_gz_end");
extern const std::uint8_t voice_en_filament_attention_start[] asm("_binary_voice_en_filament_attention_adpcm_gz_start");
extern const std::uint8_t voice_en_filament_attention_end[] asm("_binary_voice_en_filament_attention_adpcm_gz_end");
extern const std::uint8_t voice_en_shutdown_start[] asm("_binary_voice_en_shutdown_adpcm_gz_start");
extern const std::uint8_t voice_en_shutdown_end[] asm("_binary_voice_en_shutdown_adpcm_gz_end");
extern const std::uint8_t voice_en_restarting_start[] asm("_binary_voice_en_restarting_adpcm_gz_start");
extern const std::uint8_t voice_en_restarting_end[] asm("_binary_voice_en_restarting_adpcm_gz_end");
extern const std::uint8_t voice_pl_startup_start[] asm("_binary_voice_pl_startup_adpcm_gz_start");
extern const std::uint8_t voice_pl_startup_end[] asm("_binary_voice_pl_startup_adpcm_gz_end");
extern const std::uint8_t voice_pl_print_started_start[] asm("_binary_voice_pl_print_started_adpcm_gz_start");
extern const std::uint8_t voice_pl_print_started_end[] asm("_binary_voice_pl_print_started_adpcm_gz_end");
extern const std::uint8_t voice_pl_progress_25_start[] asm("_binary_voice_pl_progress_25_adpcm_gz_start");
extern const std::uint8_t voice_pl_progress_25_end[] asm("_binary_voice_pl_progress_25_adpcm_gz_end");
extern const std::uint8_t voice_pl_progress_50_start[] asm("_binary_voice_pl_progress_50_adpcm_gz_start");
extern const std::uint8_t voice_pl_progress_50_end[] asm("_binary_voice_pl_progress_50_adpcm_gz_end");
extern const std::uint8_t voice_pl_progress_75_start[] asm("_binary_voice_pl_progress_75_adpcm_gz_start");
extern const std::uint8_t voice_pl_progress_75_end[] asm("_binary_voice_pl_progress_75_adpcm_gz_end");
extern const std::uint8_t voice_pl_print_paused_start[] asm("_binary_voice_pl_print_paused_adpcm_gz_start");
extern const std::uint8_t voice_pl_print_paused_end[] asm("_binary_voice_pl_print_paused_adpcm_gz_end");
extern const std::uint8_t voice_pl_print_finished_start[] asm("_binary_voice_pl_print_finished_adpcm_gz_start");
extern const std::uint8_t voice_pl_print_finished_end[] asm("_binary_voice_pl_print_finished_adpcm_gz_end");
extern const std::uint8_t voice_pl_print_error_start[] asm("_binary_voice_pl_print_error_adpcm_gz_start");
extern const std::uint8_t voice_pl_print_error_end[] asm("_binary_voice_pl_print_error_adpcm_gz_end");
extern const std::uint8_t voice_pl_hms_alert_start[] asm("_binary_voice_pl_hms_alert_adpcm_gz_start");
extern const std::uint8_t voice_pl_hms_alert_end[] asm("_binary_voice_pl_hms_alert_adpcm_gz_end");
extern const std::uint8_t voice_pl_filament_attention_start[] asm("_binary_voice_pl_filament_attention_adpcm_gz_start");
extern const std::uint8_t voice_pl_filament_attention_end[] asm("_binary_voice_pl_filament_attention_adpcm_gz_end");
extern const std::uint8_t voice_pl_shutdown_start[] asm("_binary_voice_pl_shutdown_adpcm_gz_start");
extern const std::uint8_t voice_pl_shutdown_end[] asm("_binary_voice_pl_shutdown_adpcm_gz_end");
extern const std::uint8_t voice_pl_restarting_start[] asm("_binary_voice_pl_restarting_adpcm_gz_start");
extern const std::uint8_t voice_pl_restarting_end[] asm("_binary_voice_pl_restarting_adpcm_gz_end");
extern const std::uint8_t voice_es_startup_start[] asm("_binary_voice_es_startup_adpcm_gz_start");
extern const std::uint8_t voice_es_startup_end[] asm("_binary_voice_es_startup_adpcm_gz_end");
extern const std::uint8_t voice_es_print_started_start[] asm("_binary_voice_es_print_started_adpcm_gz_start");
extern const std::uint8_t voice_es_print_started_end[] asm("_binary_voice_es_print_started_adpcm_gz_end");
extern const std::uint8_t voice_es_progress_25_start[] asm("_binary_voice_es_progress_25_adpcm_gz_start");
extern const std::uint8_t voice_es_progress_25_end[] asm("_binary_voice_es_progress_25_adpcm_gz_end");
extern const std::uint8_t voice_es_progress_50_start[] asm("_binary_voice_es_progress_50_adpcm_gz_start");
extern const std::uint8_t voice_es_progress_50_end[] asm("_binary_voice_es_progress_50_adpcm_gz_end");
extern const std::uint8_t voice_es_progress_75_start[] asm("_binary_voice_es_progress_75_adpcm_gz_start");
extern const std::uint8_t voice_es_progress_75_end[] asm("_binary_voice_es_progress_75_adpcm_gz_end");
extern const std::uint8_t voice_es_print_paused_start[] asm("_binary_voice_es_print_paused_adpcm_gz_start");
extern const std::uint8_t voice_es_print_paused_end[] asm("_binary_voice_es_print_paused_adpcm_gz_end");
extern const std::uint8_t voice_es_print_finished_start[] asm("_binary_voice_es_print_finished_adpcm_gz_start");
extern const std::uint8_t voice_es_print_finished_end[] asm("_binary_voice_es_print_finished_adpcm_gz_end");
extern const std::uint8_t voice_es_print_error_start[] asm("_binary_voice_es_print_error_adpcm_gz_start");
extern const std::uint8_t voice_es_print_error_end[] asm("_binary_voice_es_print_error_adpcm_gz_end");
extern const std::uint8_t voice_es_hms_alert_start[] asm("_binary_voice_es_hms_alert_adpcm_gz_start");
extern const std::uint8_t voice_es_hms_alert_end[] asm("_binary_voice_es_hms_alert_adpcm_gz_end");
extern const std::uint8_t voice_es_filament_attention_start[] asm("_binary_voice_es_filament_attention_adpcm_gz_start");
extern const std::uint8_t voice_es_filament_attention_end[] asm("_binary_voice_es_filament_attention_adpcm_gz_end");
extern const std::uint8_t voice_es_shutdown_start[] asm("_binary_voice_es_shutdown_adpcm_gz_start");
extern const std::uint8_t voice_es_shutdown_end[] asm("_binary_voice_es_shutdown_adpcm_gz_end");
extern const std::uint8_t voice_es_restarting_start[] asm("_binary_voice_es_restarting_adpcm_gz_start");
extern const std::uint8_t voice_es_restarting_end[] asm("_binary_voice_es_restarting_adpcm_gz_end");
extern const std::uint8_t voice_fr_startup_start[] asm("_binary_voice_fr_startup_adpcm_gz_start");
extern const std::uint8_t voice_fr_startup_end[] asm("_binary_voice_fr_startup_adpcm_gz_end");
extern const std::uint8_t voice_fr_print_started_start[] asm("_binary_voice_fr_print_started_adpcm_gz_start");
extern const std::uint8_t voice_fr_print_started_end[] asm("_binary_voice_fr_print_started_adpcm_gz_end");
extern const std::uint8_t voice_fr_progress_25_start[] asm("_binary_voice_fr_progress_25_adpcm_gz_start");
extern const std::uint8_t voice_fr_progress_25_end[] asm("_binary_voice_fr_progress_25_adpcm_gz_end");
extern const std::uint8_t voice_fr_progress_50_start[] asm("_binary_voice_fr_progress_50_adpcm_gz_start");
extern const std::uint8_t voice_fr_progress_50_end[] asm("_binary_voice_fr_progress_50_adpcm_gz_end");
extern const std::uint8_t voice_fr_progress_75_start[] asm("_binary_voice_fr_progress_75_adpcm_gz_start");
extern const std::uint8_t voice_fr_progress_75_end[] asm("_binary_voice_fr_progress_75_adpcm_gz_end");
extern const std::uint8_t voice_fr_print_paused_start[] asm("_binary_voice_fr_print_paused_adpcm_gz_start");
extern const std::uint8_t voice_fr_print_paused_end[] asm("_binary_voice_fr_print_paused_adpcm_gz_end");
extern const std::uint8_t voice_fr_print_finished_start[] asm("_binary_voice_fr_print_finished_adpcm_gz_start");
extern const std::uint8_t voice_fr_print_finished_end[] asm("_binary_voice_fr_print_finished_adpcm_gz_end");
extern const std::uint8_t voice_fr_print_error_start[] asm("_binary_voice_fr_print_error_adpcm_gz_start");
extern const std::uint8_t voice_fr_print_error_end[] asm("_binary_voice_fr_print_error_adpcm_gz_end");
extern const std::uint8_t voice_fr_hms_alert_start[] asm("_binary_voice_fr_hms_alert_adpcm_gz_start");
extern const std::uint8_t voice_fr_hms_alert_end[] asm("_binary_voice_fr_hms_alert_adpcm_gz_end");
extern const std::uint8_t voice_fr_filament_attention_start[] asm("_binary_voice_fr_filament_attention_adpcm_gz_start");
extern const std::uint8_t voice_fr_filament_attention_end[] asm("_binary_voice_fr_filament_attention_adpcm_gz_end");
extern const std::uint8_t voice_fr_shutdown_start[] asm("_binary_voice_fr_shutdown_adpcm_gz_start");
extern const std::uint8_t voice_fr_shutdown_end[] asm("_binary_voice_fr_shutdown_adpcm_gz_end");
extern const std::uint8_t voice_fr_restarting_start[] asm("_binary_voice_fr_restarting_adpcm_gz_start");
extern const std::uint8_t voice_fr_restarting_end[] asm("_binary_voice_fr_restarting_adpcm_gz_end");
extern const std::uint8_t voice_de_startup_start[] asm("_binary_voice_de_startup_adpcm_gz_start");
extern const std::uint8_t voice_de_startup_end[] asm("_binary_voice_de_startup_adpcm_gz_end");
extern const std::uint8_t voice_de_print_started_start[] asm("_binary_voice_de_print_started_adpcm_gz_start");
extern const std::uint8_t voice_de_print_started_end[] asm("_binary_voice_de_print_started_adpcm_gz_end");
extern const std::uint8_t voice_de_progress_25_start[] asm("_binary_voice_de_progress_25_adpcm_gz_start");
extern const std::uint8_t voice_de_progress_25_end[] asm("_binary_voice_de_progress_25_adpcm_gz_end");
extern const std::uint8_t voice_de_progress_50_start[] asm("_binary_voice_de_progress_50_adpcm_gz_start");
extern const std::uint8_t voice_de_progress_50_end[] asm("_binary_voice_de_progress_50_adpcm_gz_end");
extern const std::uint8_t voice_de_progress_75_start[] asm("_binary_voice_de_progress_75_adpcm_gz_start");
extern const std::uint8_t voice_de_progress_75_end[] asm("_binary_voice_de_progress_75_adpcm_gz_end");
extern const std::uint8_t voice_de_print_paused_start[] asm("_binary_voice_de_print_paused_adpcm_gz_start");
extern const std::uint8_t voice_de_print_paused_end[] asm("_binary_voice_de_print_paused_adpcm_gz_end");
extern const std::uint8_t voice_de_print_finished_start[] asm("_binary_voice_de_print_finished_adpcm_gz_start");
extern const std::uint8_t voice_de_print_finished_end[] asm("_binary_voice_de_print_finished_adpcm_gz_end");
extern const std::uint8_t voice_de_print_error_start[] asm("_binary_voice_de_print_error_adpcm_gz_start");
extern const std::uint8_t voice_de_print_error_end[] asm("_binary_voice_de_print_error_adpcm_gz_end");
extern const std::uint8_t voice_de_hms_alert_start[] asm("_binary_voice_de_hms_alert_adpcm_gz_start");
extern const std::uint8_t voice_de_hms_alert_end[] asm("_binary_voice_de_hms_alert_adpcm_gz_end");
extern const std::uint8_t voice_de_filament_attention_start[] asm("_binary_voice_de_filament_attention_adpcm_gz_start");
extern const std::uint8_t voice_de_filament_attention_end[] asm("_binary_voice_de_filament_attention_adpcm_gz_end");
extern const std::uint8_t voice_de_shutdown_start[] asm("_binary_voice_de_shutdown_adpcm_gz_start");
extern const std::uint8_t voice_de_shutdown_end[] asm("_binary_voice_de_shutdown_adpcm_gz_end");
extern const std::uint8_t voice_de_restarting_start[] asm("_binary_voice_de_restarting_adpcm_gz_start");
extern const std::uint8_t voice_de_restarting_end[] asm("_binary_voice_de_restarting_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_startup_start[] asm("_binary_voice_zh_cn_startup_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_startup_end[] asm("_binary_voice_zh_cn_startup_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_print_started_start[] asm("_binary_voice_zh_cn_print_started_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_print_started_end[] asm("_binary_voice_zh_cn_print_started_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_progress_25_start[] asm("_binary_voice_zh_cn_progress_25_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_progress_25_end[] asm("_binary_voice_zh_cn_progress_25_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_progress_50_start[] asm("_binary_voice_zh_cn_progress_50_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_progress_50_end[] asm("_binary_voice_zh_cn_progress_50_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_progress_75_start[] asm("_binary_voice_zh_cn_progress_75_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_progress_75_end[] asm("_binary_voice_zh_cn_progress_75_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_print_paused_start[] asm("_binary_voice_zh_cn_print_paused_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_print_paused_end[] asm("_binary_voice_zh_cn_print_paused_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_print_finished_start[] asm("_binary_voice_zh_cn_print_finished_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_print_finished_end[] asm("_binary_voice_zh_cn_print_finished_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_print_error_start[] asm("_binary_voice_zh_cn_print_error_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_print_error_end[] asm("_binary_voice_zh_cn_print_error_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_hms_alert_start[] asm("_binary_voice_zh_cn_hms_alert_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_hms_alert_end[] asm("_binary_voice_zh_cn_hms_alert_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_filament_attention_start[] asm("_binary_voice_zh_cn_filament_attention_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_filament_attention_end[] asm("_binary_voice_zh_cn_filament_attention_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_shutdown_start[] asm("_binary_voice_zh_cn_shutdown_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_shutdown_end[] asm("_binary_voice_zh_cn_shutdown_adpcm_gz_end");
extern const std::uint8_t voice_zh_cn_restarting_start[] asm("_binary_voice_zh_cn_restarting_adpcm_gz_start");
extern const std::uint8_t voice_zh_cn_restarting_end[] asm("_binary_voice_zh_cn_restarting_adpcm_gz_end");

inline constexpr CompressedSample modern_startup{modern_startup_start, modern_startup_end, 4324};
inline constexpr CompressedSample modern_navigation{modern_navigation_start, modern_navigation_end, 358};
inline constexpr CompressedSample modern_orientation{modern_orientation_start, modern_orientation_end, 1126};
inline constexpr CompressedSample modern_print_started{modern_print_started_start, modern_print_started_end, 4223};
inline constexpr CompressedSample modern_print_paused{modern_print_paused_start, modern_print_paused_end, 2078};
inline constexpr CompressedSample modern_print_finished{modern_print_finished_start, modern_print_finished_end, 3935};
inline constexpr CompressedSample modern_print_error{modern_print_error_start, modern_print_error_end, 4280};
inline constexpr CompressedSample modern_hms_alert{modern_hms_alert_start, modern_hms_alert_end, 1548};
inline constexpr CompressedSample modern_filament_attention{modern_filament_attention_start, modern_filament_attention_end, 2672};
inline constexpr CompressedSample modern_shutdown_countdown{modern_shutdown_countdown_start, modern_shutdown_countdown_end, 450};
inline constexpr CompressedSample modern_shutdown{modern_shutdown_start, modern_shutdown_end, 2595};
inline constexpr CompressedSample modern_test{modern_test_start, modern_test_end, 2588};
inline constexpr CompressedSample arcade_startup{arcade_startup_start, arcade_startup_end, 9625};
inline constexpr CompressedSample arcade_navigation{arcade_navigation_start, arcade_navigation_end, 3564};
inline constexpr CompressedSample arcade_orientation{arcade_orientation_start, arcade_orientation_end, 3146};
inline constexpr CompressedSample arcade_print_started{arcade_print_started_start, arcade_print_started_end, 4609};
inline constexpr CompressedSample arcade_progress_25{arcade_progress_25_start, arcade_progress_25_end, 3564};
inline constexpr CompressedSample arcade_progress_50{arcade_progress_50_start, arcade_progress_50_end, 4191};
inline constexpr CompressedSample arcade_progress_75{arcade_progress_75_start, arcade_progress_75_end, 9625};
inline constexpr CompressedSample arcade_print_paused{arcade_print_paused_start, arcade_print_paused_end, 5862};
inline constexpr CompressedSample arcade_print_finished{arcade_print_finished_start, arcade_print_finished_end, 6628};
inline constexpr CompressedSample arcade_print_error{arcade_print_error_start, arcade_print_error_end, 10670};
inline constexpr CompressedSample arcade_hms_alert{arcade_hms_alert_start, arcade_hms_alert_end, 7906};
inline constexpr CompressedSample arcade_filament_attention{arcade_filament_attention_start, arcade_filament_attention_end, 6938};
inline constexpr CompressedSample arcade_shutdown_countdown{arcade_shutdown_countdown_start, arcade_shutdown_countdown_end, 5298};
inline constexpr CompressedSample arcade_shutdown{arcade_shutdown_start, arcade_shutdown_end, 4191};
inline constexpr CompressedSample arcade_test{arcade_test_start, arcade_test_end, 9625};
inline constexpr CompressedSample scifi_startup{scifi_startup_start, scifi_startup_end, 7644};
inline constexpr CompressedSample scifi_navigation{scifi_navigation_start, scifi_navigation_end, 1925};
inline constexpr CompressedSample scifi_orientation{scifi_orientation_start, scifi_orientation_end, 2052};
inline constexpr CompressedSample scifi_print_started{scifi_print_started_start, scifi_print_started_end, 4241};
inline constexpr CompressedSample scifi_progress_25{scifi_progress_25_start, scifi_progress_25_end, 2766};
inline constexpr CompressedSample scifi_progress_50{scifi_progress_50_start, scifi_progress_50_end, 2241};
inline constexpr CompressedSample scifi_progress_75{scifi_progress_75_start, scifi_progress_75_end, 5557};
inline constexpr CompressedSample scifi_print_paused{scifi_print_paused_start, scifi_print_paused_end, 7647};
inline constexpr CompressedSample scifi_print_finished{scifi_print_finished_start, scifi_print_finished_end, 4241};
inline constexpr CompressedSample scifi_print_error{scifi_print_error_start, scifi_print_error_end, 6231};
inline constexpr CompressedSample scifi_hms_alert{scifi_hms_alert_start, scifi_hms_alert_end, 5780};
inline constexpr CompressedSample scifi_filament_attention{scifi_filament_attention_start, scifi_filament_attention_end, 4012};
inline constexpr CompressedSample scifi_shutdown_countdown{scifi_shutdown_countdown_start, scifi_shutdown_countdown_end, 2050};
inline constexpr CompressedSample scifi_shutdown{scifi_shutdown_start, scifi_shutdown_end, 4265};
inline constexpr CompressedSample scifi_test{scifi_shutdown_countdown_start, scifi_shutdown_countdown_end, 2050};
inline constexpr CompressedSample clean_navigation{clean_navigation_start, clean_navigation_end, 566};
inline constexpr CompressedSample clean_orientation{clean_orientation_start, clean_orientation_end, 277};
inline constexpr CompressedSample clean_shutdown_countdown{clean_shutdown_countdown_start, clean_shutdown_countdown_end, 458};
inline constexpr CompressedSample clean_test{clean_test_start, clean_test_end, 1977};
inline constexpr CompressedSample voice_en_startup{voice_en_startup_start, voice_en_startup_end, 6732};
inline constexpr CompressedSample voice_en_print_started{voice_en_print_started_start, voice_en_print_started_end, 5896};
inline constexpr CompressedSample voice_en_progress_25{voice_en_progress_25_start, voice_en_progress_25_end, 16268};
inline constexpr CompressedSample voice_en_progress_50{voice_en_progress_50_start, voice_en_progress_50_end, 13713};
inline constexpr CompressedSample voice_en_progress_75{voice_en_progress_75_start, voice_en_progress_75_end, 21901};
inline constexpr CompressedSample voice_en_print_paused{voice_en_print_paused_start, voice_en_print_paused_end, 5525};
inline constexpr CompressedSample voice_en_print_finished{voice_en_print_finished_start, voice_en_print_finished_end, 18956};
inline constexpr CompressedSample voice_en_print_error{voice_en_print_error_start, voice_en_print_error_end, 9155};
inline constexpr CompressedSample voice_en_hms_alert{voice_en_hms_alert_start, voice_en_hms_alert_end, 10552};
inline constexpr CompressedSample voice_en_filament_attention{voice_en_filament_attention_start, voice_en_filament_attention_end, 6646};
inline constexpr CompressedSample voice_en_shutdown{voice_en_shutdown_start, voice_en_shutdown_end, 4049};
inline constexpr CompressedSample voice_en_restarting{voice_en_restarting_start, voice_en_restarting_end, 10436};
inline constexpr CompressedSample voice_pl_startup{voice_pl_startup_start, voice_pl_startup_end, 9691};
inline constexpr CompressedSample voice_pl_print_started{voice_pl_print_started_start, voice_pl_print_started_end, 8884};
inline constexpr CompressedSample voice_pl_progress_25{voice_pl_progress_25_start, voice_pl_progress_25_end, 19180};
inline constexpr CompressedSample voice_pl_progress_50{voice_pl_progress_50_start, voice_pl_progress_50_end, 13530};
inline constexpr CompressedSample voice_pl_progress_75{voice_pl_progress_75_start, voice_pl_progress_75_end, 23833};
inline constexpr CompressedSample voice_pl_print_paused{voice_pl_print_paused_start, voice_pl_print_paused_end, 8742};
inline constexpr CompressedSample voice_pl_print_finished{voice_pl_print_finished_start, voice_pl_print_finished_end, 20245};
inline constexpr CompressedSample voice_pl_print_error{voice_pl_print_error_start, voice_pl_print_error_end, 11949};
inline constexpr CompressedSample voice_pl_hms_alert{voice_pl_hms_alert_start, voice_pl_hms_alert_end, 12865};
inline constexpr CompressedSample voice_pl_filament_attention{voice_pl_filament_attention_start, voice_pl_filament_attention_end, 7673};
inline constexpr CompressedSample voice_pl_shutdown{voice_pl_shutdown_start, voice_pl_shutdown_end, 5858};
inline constexpr CompressedSample voice_pl_restarting{voice_pl_restarting_start, voice_pl_restarting_end, 12357};
inline constexpr CompressedSample voice_es_startup{voice_es_startup_start, voice_es_startup_end, 7140};
inline constexpr CompressedSample voice_es_print_started{voice_es_print_started_start, voice_es_print_started_end, 6706};
inline constexpr CompressedSample voice_es_progress_25{voice_es_progress_25_start, voice_es_progress_25_end, 17866};
inline constexpr CompressedSample voice_es_progress_50{voice_es_progress_50_start, voice_es_progress_50_end, 13076};
inline constexpr CompressedSample voice_es_progress_75{voice_es_progress_75_start, voice_es_progress_75_end, 21830};
inline constexpr CompressedSample voice_es_print_paused{voice_es_print_paused_start, voice_es_print_paused_end, 6427};
inline constexpr CompressedSample voice_es_print_finished{voice_es_print_finished_start, voice_es_print_finished_end, 18041};
inline constexpr CompressedSample voice_es_print_error{voice_es_print_error_start, voice_es_print_error_end, 10982};
inline constexpr CompressedSample voice_es_hms_alert{voice_es_hms_alert_start, voice_es_hms_alert_end, 10324};
inline constexpr CompressedSample voice_es_filament_attention{voice_es_filament_attention_start, voice_es_filament_attention_end, 6493};
inline constexpr CompressedSample voice_es_shutdown{voice_es_shutdown_start, voice_es_shutdown_end, 4387};
inline constexpr CompressedSample voice_es_restarting{voice_es_restarting_start, voice_es_restarting_end, 10073};
inline constexpr CompressedSample voice_fr_startup{voice_fr_startup_start, voice_fr_startup_end, 5761};
inline constexpr CompressedSample voice_fr_print_started{voice_fr_print_started_start, voice_fr_print_started_end, 6513};
inline constexpr CompressedSample voice_fr_progress_25{voice_fr_progress_25_start, voice_fr_progress_25_end, 16044};
inline constexpr CompressedSample voice_fr_progress_50{voice_fr_progress_50_start, voice_fr_progress_50_end, 15069};
inline constexpr CompressedSample voice_fr_progress_75{voice_fr_progress_75_start, voice_fr_progress_75_end, 21829};
inline constexpr CompressedSample voice_fr_print_paused{voice_fr_print_paused_start, voice_fr_print_paused_end, 6813};
inline constexpr CompressedSample voice_fr_print_finished{voice_fr_print_finished_start, voice_fr_print_finished_end, 17468};
inline constexpr CompressedSample voice_fr_print_error{voice_fr_print_error_start, voice_fr_print_error_end, 11859};
inline constexpr CompressedSample voice_fr_hms_alert{voice_fr_hms_alert_start, voice_fr_hms_alert_end, 10748};
inline constexpr CompressedSample voice_fr_filament_attention{voice_fr_filament_attention_start, voice_fr_filament_attention_end, 7133};
inline constexpr CompressedSample voice_fr_shutdown{voice_fr_shutdown_start, voice_fr_shutdown_end, 3828};
inline constexpr CompressedSample voice_fr_restarting{voice_fr_restarting_start, voice_fr_restarting_end, 10823};
inline constexpr CompressedSample voice_de_startup{voice_de_startup_start, voice_de_startup_end, 7354};
inline constexpr CompressedSample voice_de_print_started{voice_de_print_started_start, voice_de_print_started_end, 5857};
inline constexpr CompressedSample voice_de_progress_25{voice_de_progress_25_start, voice_de_progress_25_end, 19791};
inline constexpr CompressedSample voice_de_progress_50{voice_de_progress_50_start, voice_de_progress_50_end, 15696};
inline constexpr CompressedSample voice_de_progress_75{voice_de_progress_75_start, voice_de_progress_75_end, 24224};
inline constexpr CompressedSample voice_de_print_paused{voice_de_print_paused_start, voice_de_print_paused_end, 5687};
inline constexpr CompressedSample voice_de_print_finished{voice_de_print_finished_start, voice_de_print_finished_end, 17887};
inline constexpr CompressedSample voice_de_print_error{voice_de_print_error_start, voice_de_print_error_end, 9332};
inline constexpr CompressedSample voice_de_hms_alert{voice_de_hms_alert_start, voice_de_hms_alert_end, 11279};
inline constexpr CompressedSample voice_de_filament_attention{voice_de_filament_attention_start, voice_de_filament_attention_end, 6913};
inline constexpr CompressedSample voice_de_shutdown{voice_de_shutdown_start, voice_de_shutdown_end, 3904};
inline constexpr CompressedSample voice_de_restarting{voice_de_restarting_start, voice_de_restarting_end, 12269};
inline constexpr CompressedSample voice_zh_cn_startup{voice_zh_cn_startup_start, voice_zh_cn_startup_end, 8642};
inline constexpr CompressedSample voice_zh_cn_print_started{voice_zh_cn_print_started_start, voice_zh_cn_print_started_end, 7366};
inline constexpr CompressedSample voice_zh_cn_progress_25{voice_zh_cn_progress_25_start, voice_zh_cn_progress_25_end, 21768};
inline constexpr CompressedSample voice_zh_cn_progress_50{voice_zh_cn_progress_50_start, voice_zh_cn_progress_50_end, 19814};
inline constexpr CompressedSample voice_zh_cn_progress_75{voice_zh_cn_progress_75_start, voice_zh_cn_progress_75_end, 22782};
inline constexpr CompressedSample voice_zh_cn_print_paused{voice_zh_cn_print_paused_start, voice_zh_cn_print_paused_end, 7621};
inline constexpr CompressedSample voice_zh_cn_print_finished{voice_zh_cn_print_finished_start, voice_zh_cn_print_finished_end, 18815};
inline constexpr CompressedSample voice_zh_cn_print_error{voice_zh_cn_print_error_start, voice_zh_cn_print_error_end, 15316};
inline constexpr CompressedSample voice_zh_cn_hms_alert{voice_zh_cn_hms_alert_start, voice_zh_cn_hms_alert_end, 9800};
inline constexpr CompressedSample voice_zh_cn_filament_attention{voice_zh_cn_filament_attention_start, voice_zh_cn_filament_attention_end, 10415};
inline constexpr CompressedSample voice_zh_cn_shutdown{voice_zh_cn_shutdown_start, voice_zh_cn_shutdown_end, 3555};
inline constexpr CompressedSample voice_zh_cn_restarting{voice_zh_cn_restarting_start, voice_zh_cn_restarting_end, 11885};

}  // namespace printdeck::platform::audio_assets
